// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum AndroidAuthenticatorStatus {
  success,
  noHardwareAvailable,
  unavailable,
  noneEnrolled,
  securityUpdateRequired,
  unsupportedOSVersion,
  unknown,
}

enum AndroidAuthenticatorType {
  biometric,
  deviceCredential,
}

enum AndroidAuthenticationResultStatus {
  success,
  canceled,
  failed,
  error,
  negativeButtonClicked,
}

class AndroidAuthenticationFailure {
  AndroidAuthenticationFailure({
    required this.code,
    this.message,
  });

  String code;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAuthenticationFailure decode(Object result) {
    result as List<Object?>;
    return AndroidAuthenticationFailure(
      code: result[0]! as String,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAuthenticationFailure || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(code, other.code) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAuthenticationFailure(code: $code, message: $message)';
  }
}

class AndroidAuthenticationNegativeButtonClickResult {
  AndroidAuthenticationNegativeButtonClickResult({
    required this.which,
  });

  int which;

  List<Object?> _toList() {
    return <Object?>[
      which,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAuthenticationNegativeButtonClickResult decode(Object result) {
    result as List<Object?>;
    return AndroidAuthenticationNegativeButtonClickResult(
      which: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAuthenticationNegativeButtonClickResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(which, other.which);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAuthenticationNegativeButtonClickResult(which: $which)';
  }
}

class AndroidAuthenticationResult {
  AndroidAuthenticationResult({
    required this.status,
    this.failure,
    this.negativeButtonClickResult,
  });

  AndroidAuthenticationResultStatus status;

  AndroidAuthenticationFailure? failure;

  AndroidAuthenticationNegativeButtonClickResult? negativeButtonClickResult;

  List<Object?> _toList() {
    return <Object?>[
      status,
      failure,
      negativeButtonClickResult,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAuthenticationResult decode(Object result) {
    result as List<Object?>;
    return AndroidAuthenticationResult(
      status: result[0]! as AndroidAuthenticationResultStatus,
      failure: result[1] as AndroidAuthenticationFailure?,
      negativeButtonClickResult: result[2] as AndroidAuthenticationNegativeButtonClickResult?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAuthenticationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(failure, other.failure) && _deepEquals(negativeButtonClickResult, other.negativeButtonClickResult);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAuthenticationResult(status: $status, failure: $failure, negativeButtonClickResult: $negativeButtonClickResult)';
  }
}

class AndroidSecureEncryptAuthResult {
  AndroidSecureEncryptAuthResult({
    required this.status,
    this.encodedIVKey,
    this.encryptedResult,
    this.failure,
    this.negativeButtonClickResult,
  });

  AndroidAuthenticationResultStatus status;

  String? encodedIVKey;

  Map<String, String?>? encryptedResult;

  AndroidAuthenticationFailure? failure;

  AndroidAuthenticationNegativeButtonClickResult? negativeButtonClickResult;

  List<Object?> _toList() {
    return <Object?>[
      status,
      encodedIVKey,
      encryptedResult,
      failure,
      negativeButtonClickResult,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSecureEncryptAuthResult decode(Object result) {
    result as List<Object?>;
    return AndroidSecureEncryptAuthResult(
      status: result[0]! as AndroidAuthenticationResultStatus,
      encodedIVKey: result[1] as String?,
      encryptedResult: (result[2] as Map<Object?, Object?>?)?.cast<String, String?>(),
      failure: result[3] as AndroidAuthenticationFailure?,
      negativeButtonClickResult: result[4] as AndroidAuthenticationNegativeButtonClickResult?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSecureEncryptAuthResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(encodedIVKey, other.encodedIVKey) && _deepEquals(encryptedResult, other.encryptedResult) && _deepEquals(failure, other.failure) && _deepEquals(negativeButtonClickResult, other.negativeButtonClickResult);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSecureEncryptAuthResult(status: $status, encodedIVKey: $encodedIVKey, encryptedResult: $encryptedResult, failure: $failure, negativeButtonClickResult: $negativeButtonClickResult)';
  }
}

class AndroidSecureDecryptAuthResult {
  AndroidSecureDecryptAuthResult({
    required this.status,
    this.decryptedResult,
    this.failure,
    this.negativeButtonClickResult,
  });

  AndroidAuthenticationResultStatus status;

  Map<String, String?>? decryptedResult;

  AndroidAuthenticationFailure? failure;

  AndroidAuthenticationNegativeButtonClickResult? negativeButtonClickResult;

  List<Object?> _toList() {
    return <Object?>[
      status,
      decryptedResult,
      failure,
      negativeButtonClickResult,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSecureDecryptAuthResult decode(Object result) {
    result as List<Object?>;
    return AndroidSecureDecryptAuthResult(
      status: result[0]! as AndroidAuthenticationResultStatus,
      decryptedResult: (result[1] as Map<Object?, Object?>?)?.cast<String, String?>(),
      failure: result[2] as AndroidAuthenticationFailure?,
      negativeButtonClickResult: result[3] as AndroidAuthenticationNegativeButtonClickResult?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSecureDecryptAuthResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(decryptedResult, other.decryptedResult) && _deepEquals(failure, other.failure) && _deepEquals(negativeButtonClickResult, other.negativeButtonClickResult);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSecureDecryptAuthResult(status: $status, decryptedResult: $decryptedResult, failure: $failure, negativeButtonClickResult: $negativeButtonClickResult)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AndroidAuthenticatorStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAuthenticatorType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAuthenticationResultStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAuthenticationFailure) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidAuthenticationNegativeButtonClickResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidAuthenticationResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSecureEncryptAuthResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSecureDecryptAuthResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidAuthenticatorStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidAuthenticatorType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidAuthenticationResultStatus.values[value];
      case 132:
        return AndroidAuthenticationFailure.decode(readValue(buffer)!);
      case 133:
        return AndroidAuthenticationNegativeButtonClickResult.decode(readValue(buffer)!);
      case 134:
        return AndroidAuthenticationResult.decode(readValue(buffer)!);
      case 135:
        return AndroidSecureEncryptAuthResult.decode(readValue(buffer)!);
      case 136:
        return AndroidSecureDecryptAuthResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MarkApi {
  /// Constructor for [MarkApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MarkApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> deleteSecretKey(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.deleteSecretKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isDeviceSupportFingerprint() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isDeviceSupportFingerprint$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isDeviceSupportFaceAuth() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isDeviceSupportFaceAuth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isDeviceSupportBiometric() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isDeviceSupportBiometric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isFingerprintEnrolled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isFingerprintEnrolled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> isDeviceCredentialEnrolled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isDeviceCredentialEnrolled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<AndroidAuthenticatorStatus> checkAuthenticatorStatus(AndroidAuthenticatorType androidAuthenticatorType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.checkAuthenticatorStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[androidAuthenticatorType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAuthenticatorStatus;
  }

  Future<AndroidAuthenticatorStatus> checkSecureAuthenticatorStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.checkSecureAuthenticatorStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAuthenticatorStatus;
  }

  Future<bool> canAuthenticate({required AndroidAuthenticatorType androidAuthenticatorType}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.canAuthenticate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[androidAuthenticatorType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<AndroidAuthenticationResult> authenticateDeviceCredential({required String title, String? subTitle, required String description, required String negativeText, required bool confirmationRequired, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.authenticateDeviceCredential$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[title, subTitle, description, negativeText, confirmationRequired]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAuthenticationResult;
  }

  Future<AndroidAuthenticationResult> authenticateBiometric({required String title, String? subTitle, required String description, required String negativeText, required bool confirmationRequired, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.authenticateBiometric$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[title, subTitle, description, negativeText, confirmationRequired]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAuthenticationResult;
  }

  Future<bool> isBiometricChanged({required String alias}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.isBiometricChanged$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<AndroidSecureEncryptAuthResult> authenticateBiometricSecureEncrypt({required String alias, required Map<String, String> requestForEncrypt, required String title, String? subTitle, required String description, required String negativeText, required bool confirmationRequired, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.authenticateBiometricSecureEncrypt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias, requestForEncrypt, title, subTitle, description, negativeText, confirmationRequired]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidSecureEncryptAuthResult;
  }

  Future<AndroidSecureDecryptAuthResult> authenticateBiometricSecureDecrypt({required String alias, required String encodedIVKey, required Map<String, String> requestForDecrypt, required String title, String? subTitle, required String description, required String negativeText, required bool confirmationRequired, }) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mark_android.MarkApi.authenticateBiometricSecureDecrypt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias, encodedIVKey, requestForDecrypt, title, subTitle, description, negativeText, confirmationRequired]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidSecureDecryptAuthResult;
  }
}
