name: mark_platform_interface
description: "Mark Platform Interface"
version: 0.0.1
homepage: https://github.com/fadlurahmanfdev/mark

environment:
  sdk: '^3.0.0'

dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^5.0.0
