name: Create Android Release & Publish Android to Pub Dev

on:
  push:
    tags:
      - 'mark-android-v*'

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/reusable-pub-flow.yml
    with:
      mode: publish
      package_path: mark_android
      tag_prefix: mark-android-v
      release_name_prefix: Mark Android
          
