name: iOS Pre Release (Dry Run Publish Pub Dev)

on:
  pull_request:
    branches:
      - master

jobs:
  pre_release:
    uses: ./.github/workflows/reusable-pub-flow.yml
    with:
      mode: pre_release
      package_path: mark_ios
