name: Create iOS Release & Publish iOS to Pub Dev

on:
  push:
    tags:
      - 'mark-ios-v*'

jobs:
  publish:
    uses: ./.github/workflows/reusable-pub-flow.yml
    with:
      mode: publish
      package_path: mark_ios
      tag_prefix: mark-ios-v
      release_name_prefix: Mark iOS
          
