name: Create Platform Release & Publish Platform to Pub Dev

on:
  push:
    tags:
      - 'mark-platform-v*'

jobs:
  publish:
    uses: ./.github/workflows/reusable-pub-flow.yml
    with:
      mode: publish
      package_path: mark_platform_interface
      tag_prefix: mark-platform-v
      release_name_prefix: Mark Platform
    secrets: inherit
          
