name: Create Release & Publish to Pub Dev

on:
  push:
    tags:
      - 'mark-v*'

jobs:
  publish:
    uses: ./.github/workflows/reusable-pub-flow.yml
    with:
      mode: publish
      package_path: mark_biometric
      tag_prefix: mark-v
      release_name_prefix: Mark
    secrets: inherit
          
